import type { Metadata } from 'next';

import './globals.css';
import Providers from './_providers/Providers';
import Appbar from './_components/Appbar';
import Footer from './_components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Appbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
